// Mocks generated by Mockito 5.4.4 from annotations
// in send_money_app/test/unit_test/features/transaction/transaction_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:send_money_app/features/transaction/domain/models/transaction_model.dart'
    as _i2;
import 'package:send_money_app/features/transaction/domain/repositories/i_transaction_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTransactionModel_0 extends _i1.SmartFake
    implements _i2.TransactionModel {
  _FakeTransactionModel_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ITransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockITransactionRepository extends _i1.Mock
    implements _i3.ITransactionRepository {
  @override
  _i4.Future<_i2.TransactionModel> sendMoney({
    required String? name,
    required double? amount,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendMoney,
          [],
          {
            #name: name,
            #amount: amount,
          },
        ),
        returnValue:
            _i4.Future<_i2.TransactionModel>.value(_FakeTransactionModel_0(
          this,
          Invocation.method(
            #sendMoney,
            [],
            {
              #name: name,
              #amount: amount,
            },
          ),
        )),
        returnValueForMissingStub:
            _i4.Future<_i2.TransactionModel>.value(_FakeTransactionModel_0(
          this,
          Invocation.method(
            #sendMoney,
            [],
            {
              #name: name,
              #amount: amount,
            },
          ),
        )),
      ) as _i4.Future<_i2.TransactionModel>);
}
